name: woodoo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  connectivity_plus: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
  generate: true

flavorizr:
  app:
    android:
      flavorDimensions: "environment"
    ios:
      bundleIdPrefix: "com.woodoo"

  flavors:
    dev:
      app:
        name: "Woodoo Dev"
      android:
        applicationId: "com.woodoo.dev"
      ios:
        bundleId: "com.woodoo.dev"
      dart:
        entrypoint: lib/main_dev.dart

    uat:
      app:
        name: "Woodoo UAT"
      android:
        applicationId: "com.woodoo.uat"
      ios:
        bundleId: "com.woodoo.uat"
      dart:
        entrypoint: lib/main_uat.dart

    prod:
      app:
        name: "Woodoo"
      android:
        applicationId: "com.woodoo"
      ios:
        bundleId: "com.woodoo"
      dart:
        entrypoint: lib/main_prod.dart
